[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
platform_packages =
    platformio/toolchain-gccarmnoneeabi@1.140201.0
    platformio/tool-openocd@2.1100.211028

build_src_filter =
    +<*>
    +<../Core/Src/*.c>
    +<../Core/Startup/*.s>
    +<../Middlewares/Third_Party/FreeRTOS/Source/*.c>
    +<../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/*.c>
    +<../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/*.c>
    +<../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>

build_flags =
    -I Core/Inc
    -I Drivers/STM32F1xx_HAL_Driver/Inc
    -I Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
    -I Drivers/CMSIS/Device/ST/STM32F1xx/Include
    -I Drivers/CMSIS/Include
    -I Middlewares/Third_Party/FreeRTOS/Source/include
    -I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
    -I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3

debug_build_flags = -Og -g

board_build.ldscript = STM32F103C8TX_FLASH.ld

upload_protocol = stlink
debug_tool = stlink